
name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Reddit
      REDDIT_CLIENT_ID : 'fake_id'
      REDDIT_CLIENT_SECRET : 'fake_secret'
      REDDIT_USER_AGENT : 'fake_user_agent'
      REDDIT_USERNAME : 'fake_reddit_username'
      REDDIT_PASSWORD : 'fake_reddit_password'

      # Discord
      DISCORD_TOKEN : "fake_token"
      NEW_POSTS_CHANNEL_ID : 1
      MODMAIL_CHANNEL_ID : 3
      BOT_COMMANDS_CHANNEL_ID : 4
      ROSTER_NEWS_CHANNEL_ID : 5
      SCHEDULE_CHAT_CHANNEL_ID : 6
      MODLOG_CHANNEL_ID : 7
      developer_name : 'fake_name'
      developer_discriminator : 'fake_discriminator'
      VERIFIED_MODERATORS : "[]"
      MODERATOR_EMAILS: "[]"

      # PostgreSQL
      DB_NAME : 'fake_db_name'
      DB_HOST : 'fake_db_host'
      DB_USER : 'fake_db_user'
      DB_PORT : '1'
      DB_PASSWORD : 'fake_db_password'

      # Pastebin
      PASTEBIN_API_KEY : "fake_pastebin_api_key"
      PASTEBIN_API_USER_KEY : "fake_pastebin_user_key"
      PASTEBIN_USER_NAME : "fake_pastebin_username"
      PASTEBIN_USER_PASS : "fake_pastebin_password"
      PASTEEE_APP_KEY : "fake_pasteee_app_key"

      # Google
      CALENDAR_ID : "fake_calendar_id"
      SHEETS_ID : "fake_sheets_id"
      GOOGLE_CREDENTIALS_JSON : "{}"

      # Indicator for Running Mode
      RUNNING_MODE : "production"

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print ENV
        run: python -c "import os; print(os.environ)"
        
      - name: Run Tests
        run: python -m unittest -f --locals -v
        
      - name: Generate Codecov Report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
        
      - name: Upload Codecov Report
        uses: codecov/codecov-action@v3.1.1
        with:
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
