
name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Reddit
      REDDIT_CLIENT_ID : 'fake_id'
      REDDIT_CLIENT_SECRET : 'fake_secret'
      REDDIT_USER_AGENT : 'fake_user_agent'
      REDDIT_USERNAME : 'fake_reddit_username'
      REDDIT_PASSWORD : 'fake_reddit_password'

      # Discord
      DISCORD_TOKEN : "fake_token"
      NEW_POSTS_CHANNEL_ID : 1
      TRELLO_CHANNEL_ID : 2
      MODMAIL_CHANNEL_ID : 3
      BOT_COMMANDS_CHANNEL_ID : 4
      ROSTER_NEWS_CHANNEL_ID : 5
      developer_name : 'fake_name'
      developer_discriminator : 'fake_discriminator'
      VERIFIED_MODERATORS : "[]"

      # PostgreSQL
      DB_NAME : 'fake_db_name'
      DB_HOST : 'fake_db_host'
      DB_USER : 'fake_db_user'
      DB_PORT : '1'
      DB_PASSWORD : 'fake_db_password'

      # Trello
      TRELLO_AUTH_KEY : "fake_trello_auth"
      TRELLO_AUTH_TOKEN : "fake_trello_auth_token"
      TRELLO_BOARD_ID : "fake_trello_board_id"

      # Pastebin
      PASTEBIN_API_KEY : "fake_pastebin_api_key"
      PASTEBIN_API_USER_KEY : "fake_pastebin_user_key"
      PASTEBIN_USER_NAME : "fake_pastebin_username"
      PASTEBIN_USER_PASS : "fake_pastebin_password"

      # Calendar
      CALENDAR_ID : "fake_calendar_id"
      GOOGLE_CREDENTIALS_JSON : "{}"

      # Indicator for Running Mode
      RUNNING_MODE : "production"

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
 
      - name: Print ENV
        run: python -c "import os; print(os.environ)" 
              
      - name: Run Tests
        run: python -m unittest -f --locals -v
